version: '3.8'

services:
  # Setup Server Container
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: vmv-server
    container_name: vmv-server-container-dev
    volumes:
      - ./server:/usr/app/server
      - /usr/app/server/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file: ./server/.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    networks:
      - vmv-app-network  
    depends_on:
      - mongo    
    command: npm run development
  # Setup Database Container
  mongo:
    image: mongo
    container_name: vmv-mongodb-container-dev
    volumes:
      - vmv-data-dev:/data/db
    env_file: ./server/.env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    networks:
      - vmv-app-network
  # Setup Client Container
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: vmv-client
    container_name: vmv-client-container-dev
    volumes:
      - ./client:/usr/app/client
      - /usr/app/client/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING='true'
    stdin_open: true
    tty: true
    env_file: ./client/.env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    networks:
      - vmv-app-network
    depends_on:
      - server 
    command: yarn start

networks:
  vmv-app-network:
    driver: bridge

volumes:
  vmv-data-dev:
