version: '3.8'

services:
  # Setup Server Container
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vmv-server
    container_name: vmv-server-dev
    volumes:
      - .:/usr/app/server
    # - /usr/app/server/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING='true'
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    networks:
      - vmv-app-network  
    depends_on:
      - mongo    
    command: npm run development
  # Setup Database Containers
  mongo:
    image: mongo
    container_name: vmv-mongodb-dev
    volumes:
      - vmv-data:/data/db
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    networks:
      - vmv-app-network
  mongo-express:
    image: mongo-express
    container_name: vmv-mongoex-dev
    env_file: .env
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    networks:
      - vmv-app-network
    depends_on:
      - mongo     
    
networks:
  vmv-app-network:
    driver: bridge
  
volumes:
  vmv-data:
    driver: local
    