//===============================================================================================================//

export const ARTIST_START_LOADING = "ARTIST_START_LOADING";
export const ARTIST_RETURN_FAILURE = "ARTIST_RETURN_FAILURE";
export const ARTIST_RESET_STATUS = "ARTIST_RESET_STATUS";

export const FETCH_ARTISTS_SEND = "FETCH_ARTISTS_SEND";
export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";

export const FETCH_ARTIST_SEND = "FETCH_ARTIST_SEND";
export const FETCH_ARTIST_SUCCESS = "FETCH_ARTIST_SUCCESS";

export const ADD_ARTIST_CLIENT_PREP = "ADD_ARTIST_CLIENT_PREP";
export const ADD_ARTIST_SEND = "ADD_ARTIST_SEND";
export const ADD_ARTIST_SUCCESS = "ADD_ARTIST_SUCCESS";

export const EDIT_ARTIST_CLIENT_PREP = "EDIT_ARTIST_CLIENT_PREP";
export const EDIT_ARTIST_CLIENT_INPUT = "EDIT_ARTIST_CLIENT_INPUT";

export const UPDATE_ARTIST_SEND = "UPDATE_ARTIST_SEND";
export const UPDATE_ARTIST_SUCCESS = "UPDATE_ARTIST_SUCCESS";

export const DELETE_ARTIST_SEND = "DELETE_ARTIST_SEND";
export const DELETE_ARTIST_SUCCESS = "DELETE_ARTIST_SUCCESS";

//===============================================================================================================//

export const LABEL_START_LOADING = "LABEL_START_LOADING";
export const LABEL_RETURN_FAILURE = "LABEL_RETURN_FAILURE";
export const LABEL_RESET_STATUS = "LABEL_RESET_STATUS";

export const FETCH_LABELS_SEND = "FETCH_LABELS_SEND";
export const FETCH_LABELS_SUCCESS = "FETCH_LABELS_SUCCESS";

export const FETCH_LABEL_SEND = "FETCH_LABEL_SEND";
export const FETCH_LABEL_SUCCESS = "FETCH_LABEL_SUCCESS";

export const ADD_LABEL_CLIENT_PREP = "ADD_LABEL_CLIENT_PREP";
export const ADD_LABEL_SEND = "ADD_LABEL_SEND";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS";

export const EDIT_LABEL_CLIENT_PREP = "EDIT_LABEL_CLIENT_PREP";
export const EDIT_LABEL_CLIENT_INPUT = "EDIT_LABEL_CLIENT_INPUT";

export const UPDATE_LABEL_SEND = "UPDATE_LABEL_SEND";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS";

export const DELETE_LABEL_SEND = "DELETE_LABEL_SEND";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";

//===============================================================================================================//

export const RELEASE_START_LOADING = "RELEASE_START_LOADING";
export const RELEASE_RETURN_FAILURE = "RELEASE_RETURN_FAILURE";
export const RELEASE_RESET_STATUS = "RELEASE_RESET_STATUS";
export const RELEASE_RESET_RESULTS = "RELEASE_RESET_RESULTS";

export const FETCH_RELEASES_SEND = "FETCH_RELEASES_SEND";
export const FETCH_RELEASES_SUCCESS = "FETCH_RELEASES_SUCCESS";

export const FETCH_RELEASE_SEND = "FETCH_RELEASE_SEND";
export const FETCH_RELEASE_SUCCESS = "FETCH_RELEASE_SUCCESS";

export const FETCH_RELEASES_BY_ARTIST_SEND = "FETCH_RELEASES_BY_ARTIST_SEND";
export const FETCH_RELEASES_BY_ARTIST_SUCCESS = "FETCH_RELEASES_BY_ARTIST_SUCCESS";

export const FETCH_RELEASES_BY_LABEL_SEND = "FETCH_RELEASES_BY_LABEL_SEND";
export const FETCH_RELEASES_BY_LABEL_SUCCESS = "FETCH_RELEASES_BY_LABEL_SUCCESS";

export const ADD_RELEASE_CLIENT_PREP = "ADD_RELEASE_CLIENT_PREP";
export const ADD_RELEASE_SEND = "ADD_RELEASE_SEND";
export const ADD_RELEASE_SUCCESS = "ADD_RELEASE_SUCCESS";

export const EDIT_RELEASE_CLIENT_PREP = "EDIT_RELEASE_CLIENT_PREP";
export const EDIT_RELEASE_CLIENT_INPUT = "EDIT_RELEASE_CLIENT_INPUT";

export const UPDATE_RELEASE_SEND = "UPDATE_RELEASE_SEND";
export const UPDATE_RELEASE_SUCCESS = "UPDATE_RELEASE_SUCCESS";

export const DELETE_RELEASE_SEND = "DELETE_RELEASE_SEND";
export const DELETE_RELEASE_SUCCESS = "DELETE_RELEASE_SUCCESS";

//===============================================================================================================//

export const TRACK_START_LOADING = "TRACK_START_LOADING";
export const TRACK_RETURN_FAILURE = "TRACK_RETURN_FAILURE";
export const TRACK_RESET_STATUS = "TRACK_RESET_STATUS";
export const TRACK_RESET_RESULTS = "TRACK_RESET_RESULTS";

export const FETCH_TRACKS_SEND = "FETCH_TRACKS_SEND";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";

export const FETCH_TRACK_SEND = "FETCH_TRACK_SEND";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const FETCH_TRACKS_BY_ARTIST_SEND = "FETCH_TRACKS_BY_ARTIST_SEND";
export const FETCH_TRACKS_BY_ARTIST_SUCCESS = "FETCH_TRACKS_BY_ARTIST_SUCCESS";

export const FETCH_TRACKS_BY_LABEL_SEND = "FETCH_TRACKS_BY_LABEL_SEND";
export const FETCH_TRACKS_BY_LABEL_SUCCESS = "FETCH_TRACKS_BY_LABEL_SUCCESS";

export const FETCH_TRACKS_BY_RELEASE_SEND = "FETCH_TRACKS_BY_RELEASE_SEND";
export const FETCH_TRACKS_BY_RELEASE_SUCCESS = "FETCH_TRACKS_BY_RELEASE_SUCCESS";

export const ADD_TRACK_CLIENT_PREP = "ADD_TRACK_CLIENT_PREP";

export const EDIT_TRACK_CLIENT_PREP = "EDIT_TRACK_CLIENT_PREP";
export const EDIT_TRACK_CLIENT_INPUT = "EDIT_TRACK_CLIENT_INPUT";

//===============================================================================================================//
